### ISSUE TITLE
Emby HomePage Add-in - Item Details URL Needs updating

### ISSUE THREAD

**Issue by whereisglenn** [causefx/Organizr#1290]
###### Operating System: Windows
<hr>

##### Problem Description:
Emby has updated their URL for item details.

Current link generated for recently added items etc.
http://app.emby.media/#!/itemdetails.html?id=[item id]

Link needs to change to http://app.emby.media/#!/item/item.html?id=[item id]

<hr>

##### Reproduction Steps:
Click Emby link button on any recently added item and item detail shows blank screen

<hr>

#### Errors on screen?  If so paste here:

```

```

**Comment by falcon397** [comment]
Second this issue and fix.  Just an update to the link should fix it.

homepage-connect-functions.php - line 254 and 255 could be updated to fix the issue.

**Comment by 1ntroduc3** [comment]
This issue still exist here.

**Comment by causefx** [comment]
totally missed all notifications on this.  fixed.

**Comment by CAPS3** [comment]
Hi CauseFX, 

I've posted under #1353 , but thought I'd provide an update here as well for brevity:

Currently running 2.0.570 and for the record, I've rebooted the Docker Host, restarted the Organizr container and the docker stack (NGINX, Jellyfin, etc) and sanity checked the configs, and can confirm the issue is still occurring.

URL that DOES NOT work (current): https://domain.com/jellyfin/#!/item/item.html?id=32bc6b3cf7262706fc4657bb5d02d879

URL that DOES works: https://domain.com/jellyfin/web/index.html?id=32bc6b3cf7262706fc4657bb5d02d879#!

Please let me know if there's some way I might be able to assist further :)
I'm happy to provide logs or further information upon request - let me know what you might need.

**Comment by whereisglenn** [comment]
Hi, could this issue be re-opened. It has never been resolved and still the issue exists. Just a simple 2min patch to the source will address this.
