### ISSUE TITLE
Mobile touches go through the side bar as well.

### ISSUE THREAD

**Issue by SgtBatten** [causefx/Organizr#5]
Doesn't appear to happen on PC.

On mobile couch potato is my 4th tab down.
I have my side bar pinned.

To reproduce:
Be using any tab.
Press couch potato icon on left. (Loads couch potato to home page and expands side menu)
Close side menu by pressing couch potato text
Side menu will close and couch potato will also change to movies page because the movies link was beneath the side bar where you just clicked.

Presumably this is not unique to couch potato but it's an example that will work every time.

**Comment by causefx** [comment]
is this during landscape?

**Comment by SgtBatten** [comment]
Both portrait and landscape are the same

**Comment by causefx** [comment]
hmmmm, I just changed some code so it auto closes if menu is open in landscape.  hopefully that fixes it.

**Comment by causefx** [comment]
it also wont auto open menu on mobile if pinned.

**Comment by SgtBatten** [comment]
Do you mean after the change?

Currently it's pinned and it automatically expands the side bar when I select a new tab

**Comment by causefx** [comment]
correct, i fixed it on my end,  Will push the commit today sometime.

**Comment by SgtBatten** [comment]
Doesn't appear to be fixed for me

**Comment by causefx** [comment]
What is the phrase

**Comment by SgtBatten** [comment]
Not sure what you mean.

The example from the opening post still happens for me.
Same as my server name still takes up 2 lines. I definitely updated everything.

**Comment by SgtBatten** [comment]
Errrgh nevermind. I must  have been viewing a cached version. Server name is good and  the tabs no longer expand on touch so that means this bug is fixed too. Thanks man

**Comment by causefx** [comment]
awesome!
